# =====================================================================
# ФАЙЛ: apps/users/context_processors.py
# Контекстный процессор для полной локализации сайта (RU / UA)
# =====================================================================

TRANSLATIONS = {
    'ru': {
        'brand': 'ByteLink',
        'feed': 'Лента',
        'friends': 'Друзья',
        'groups': 'Группы',
        'messages': 'Сообщения',
        'notifications': 'Уведомления',
        'my_profile': 'Мой профиль',
        'settings': 'Настройки',
        'admin_panel': 'Админ-панель',
        'logout': 'Выйти',
        'login': 'Войти',
        'register': 'Регистрация',
        'search_placeholder': 'Поиск пользователей...',
        'search': 'Поиск',
        'what_new': 'Что у вас нового?',
        'publish': 'Опубликовать',
        'attach_photo': 'Прикрепить фото',
        'like': 'Нравится',
        'comment': 'Комментировать',
        'comments': 'Комментарии',
        'add_comment': 'Написать комментарий...',
        'send': 'Отправить',
        'add_friend': 'Добавить в друзья',
        'remove_friend': 'Удалить из друзей',
        'request_sent': 'Заявка отправлена',
        'accept': 'Принять',
        'decline': 'Отклонить',
        'write_message': 'Написать',
        'edit_profile': 'Редактировать профиль',
        'bio': 'О себе',
        'status': 'Статус',
        'location': 'Местоположение',
        'website': 'Сайт',
        'birth_date': 'Дата рождения',
        'posts': 'Публикации',
        'subscribers': 'Участники',
        'create_group': 'Создать группу',
        'join_group': 'Вступить в группу',
        'leave_group': 'Выйти из группы',
        'group_members': 'Участники группы',
        'group_posts': 'Публикации группы',
        'no_posts': 'Пока нет публикаций',
        'no_notifications': 'Уведомлений пока нет',
        'mark_read': 'Отметить все как прочитанные',
        'username': 'Имя пользователя',
        'password': 'Пароль',
        'already_account': 'Уже есть аккаунт?',
        'no_account': 'Нет аккаунта?',
        'save': 'Сохранить',
        'cancel': 'Отмена',
    },
    'uk': {
        'brand': 'ByteLink',
        'feed': 'Стрічка',
        'friends': 'Друзі',
        'groups': 'Групи',
        'messages': 'Повідомлення',
        'notifications': 'Сповіщення',
        'my_profile': 'Мій профіль',
        'settings': 'Налаштування',
        'admin_panel': 'Адмін-панель',
        'logout': 'Вийти',
        'login': 'Увійти',
        'register': 'Реєстрація',
        'search_placeholder': 'Пошук користувачів...',
        'search': 'Пошук',
        'what_new': 'Що у вас нового?',
        'publish': 'Опублікувати',
        'attach_photo': 'Прикріпити фото',
        'like': 'Подобається',
        'comment': 'Коментувати',
        'comments': 'Коментарі',
        'add_comment': 'Написати коментар...',
        'send': 'Надіслати',
        'add_friend': 'Додати до друзів',
        'remove_friend': 'Видалити з друзів',
        'request_sent': 'Заявку надіслано',
        'accept': 'Прийняти',
        'decline': 'Відхилити',
        'write_message': 'Написати',
        'edit_profile': 'Редагувати профіль',
        'bio': 'Про себе',
        'status': 'Статус',
        'location': 'Місцезнаходження',
        'website': 'Сайт',
        'birth_date': 'Дата народження',
        'posts': 'Публікації',
        'subscribers': 'Учасники',
        'create_group': 'Створити групу',
        'join_group': 'Вступити в групу',
        'leave_group': 'Вийти з групи',
        'group_members': 'Учасники групи',
        'group_posts': 'Публікації групи',
        'no_posts': 'Поки немає публікацій',
        'no_notifications': 'Сповіщень поки немає',
        'mark_read': 'Позначити всі як прочитані',
        'username': "Ім'я користувача",
        'password': 'Пароль',
        'already_account': 'Вже є акаунт?',
        'no_account': 'Немає акаунту?',
        'save': 'Зберегти',
        'cancel': 'Скасувати',
    }
}


def translation_processor(request):
    """
    Автоматически передаёт объект переводов `t` во все HTML-шаблоны сайта
    в зависимости от языка, выбранного пользователем в сессии.
    """
    lang = request.session.get('django_language', 'uk')  # По умолчанию Украинский язык
    if lang not in TRANSLATIONS:
        lang = 'uk'
    return {
        't': TRANSLATIONS[lang],
        'current_lang': lang
    }
