# Generated by Django 5.0.14 on 2026-07-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_bumped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bumped_at',
        ),
    ]
